/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sengled_media_jni_JNIFunction_JNIFunctionHolder */

#ifndef _Included_com_sengled_media_jni_JNIFunction_JNIFunctionHolder
#define _Included_com_sengled_media_jni_JNIFunction_JNIFunctionHolder
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
