/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sengled_media_jni_JNIFunction */

#ifndef _Included_com_sengled_media_jni_JNIFunction
#define _Included_com_sengled_media_jni_JNIFunction
#ifdef __cplusplus
extern "C" {
#endif


/*
 * Class:     com_sengled_media_jni_JNIFunction
 * Method:    getLog4CFunction
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_sengled_media_jni_JNIFunction_getLog4CFunction
  (JNIEnv *, jobject);

/*
 * Class:     com_sengled_media_jni_JNIFunction
 * Method:    invokeLog4CFunction
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_sengled_media_jni_JNIFunction_invokeLog4CFunction
  (JNIEnv *, jobject, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
