version: 0.1

phases:
  install:
    commands:
      - echo "Nothing to do in the install phase..."
  pre_build:
    commands:
      export LANG=en_US.utf8
      - echo "Make begin with [`date`], ok. "
      - export LANG=en_US.utf8
      - yum -y install zlib-devel cmake
  build:
    commands:
      - echo "Build begin with [`date`]"
      - sh build-cproject.sh
      - mvn install
  post_build:
    commands:
      - echo "Build complete with [`date`]"

artifacts:
  files:
    - source: src/java/algorithm-assembly/target/media-algorithm-v3-distribution.zip
      destination: content/
      action: unzip

