package com.sengled.media.jna.naldecoder;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : /home/chenxh/workspace/gitlab.com/algorithm/src/c/decoder/src/naldecoder.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class YUVFrame extends Structure {
	public int width;
	public int height;
	/** C type : char* */
	public Pointer data;
	public int size;
	public YUVFrame() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("width", "height", "data", "size");
	}
	/** @param data C type : char* */
	public YUVFrame(int width, int height, Pointer data, int size) {
		super();
		this.width = width;
		this.height = height;
		this.data = data;
		this.size = size;
	}
	public YUVFrame(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends YUVFrame implements Structure.ByReference {
		
	};
	public static class ByValue extends YUVFrame implements Structure.ByValue {
		
	};
}
