package com.sengled.media.jna.jpg_encoder;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : jpg_encoder.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class JPGFrame extends Structure {
	/** C type : char* */
	public Pointer data;
	public int size;
	public JPGFrame() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("data", "size");
	}
	/** @param data C type : char* */
	public JPGFrame(Pointer data, int size) {
		super();
		this.data = data;
		this.size = size;
	}
	public JPGFrame(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends JPGFrame implements Structure.ByReference {
		
	};
	public static class ByValue extends JPGFrame implements Structure.ByValue {
		
	};
}
