package com.sengled.media.jna.sengled_algorithm_base;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : sengled_algorithm_base.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class algorithm_base_result2 extends Structure {
	public int bresult;
    public Pointer result;
    public int size;
	public algorithm_base_result2() {
		super();
	}
	
	public algorithm_base_result2(int bresult,Pointer data, int size) {
	        super();
	        this.bresult = bresult;
	        this.result = data;
	        this.size = size;
	}
	   
	protected List<String> getFieldOrder() {
		return Arrays.asList("bresult", "result","size");
	}

	
	public algorithm_base_result2(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends algorithm_base_result2 implements Structure.ByReference {
		
	};
	public static class ByValue extends algorithm_base_result2 implements Structure.ByValue {
		
	};
}
